<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'name' => 'iPhone X 64GB',
                'code' => 'iphone_x_64',
                'description' => 'Отличный продвинутый телефон с памятью на 64 gb',
                'price' => '71990',
                'category_id' => 1,
                'picture' => 'products/iphone_x.jpeg',
                'quantity' => rand(0,10),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
            ],
            [
                'name' => 'iPhone X 256GB',
                'code' => 'iphone_x_256',
                'description' => 'Отличный продвинутый телефон с памятью на 256 gb',
                'price' => '89990',
                'category_id' => 1,
                'picture' => 'products/iphone_x_silver.jpeg',
                'quantity' => rand(0,10),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
            ],
            [
                'name' => 'HTC One S',
                'code' => 'htc_one_s',
                'description' => 'Зачем платить за лишнее? Легендарный HTC One S',
                'price' => '12490',
                'category_id' => 1,
                'picture' => 'products/htc_one_s.png',
                'quantity' => rand(0,10),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
            ],
            [
                'name' => 'iPhone 5SE',
                'code' => 'iphone_5se',
                'description' => 'Отличный классический iPhone',
                'price' => '17221',
                'category_id' => 1,
                'picture' => 'products/iphone_5.jpeg',
                'quantity' => rand(0,10),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
            ],
            [
                'name' => 'Наушники Beats Audio',
                'code' => 'beats_audio',
                'description' => 'Отличный классический iPhone',
                'price' => '20221',
                'category_id' => 2,
                'picture' => 'products/beats.jpeg',
                'quantity' => rand(0,10),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
            ],
            [
                'name' => 'Камера GoPro',
                'code' => 'gopro',
                'description' => 'Снимай самые яркие моменты с помощью этой камеры',
                'price' => '12000',
                'category_id' => 2,
                'picture' => 'products/gopro.jpeg',
                'quantity' => rand(0,10),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
            ],
            [
                'name' => 'Камера Panasonic HC-V770',
                'code' => 'panasonic_hc-v770',
                'description' => 'Для серьёзной видео съемки нужна серьёзная камера. Panasonic HC-V770 для этих целей лучший выбор!',
                'price' => '27900',
                'category_id' => 2,
                'picture' => 'products/video_panasonic.jpeg',
                'quantity' => rand(0,10),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
            ],
            [
                'name' => 'Кофемашина DeLongi',
                'code' => 'delongi',
                'description' => 'Хорошее утро начинается с хорошего кофе!',
                'price' => '40200',
                'category_id' => 3,
                'picture' => 'products/delongi.jpeg',
                'quantity' => rand(0,10),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
            ],
            [
                'name' => 'Холодильник Haier',
                'code' => 'haier',
                'description' => 'Для большой семьи большой холодильник!',
                'price' => '40200',
                'category_id' => 3,
                'picture' => 'products/haier.jpeg',
                'quantity' => rand(0,10),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
            ],
            [
                'name' => 'Блендер Moulinex',
                'code' => 'moulinex',
                'description' => 'Для самых смелых идей',
                'price' => '4200',
                'category_id' => 3,
                'picture' => 'products/moulinex.jpeg',
                'quantity' => rand(0,10),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
            ],
            [
                'name' => 'Мясорубка Bosch',
                'code' => 'bosch',
                'description' => 'Любите домашние котлеты? Вам определенно стоит посмотреть на эту мясорубку!',
                'price' => '9200',
                'category_id' => 3,
                'picture' => 'products/bosch.jpeg',
                'quantity' => rand(0,10),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
            ],
            [
                'name' => 'Samsung Galaxy J6',
                'code' => 'galaxy_j6',
                'description' => 'Описание galaxy J6',
                'price' => '12990',
                'category_id' => 1,
                'picture' => 'products/samsung_j6.jpeg',
                'quantity' => rand(0,10),
                'hot' => rand(0,1),
                'new' => rand(0,1),
                'sale' => rand(0,1),
            ],
        ]);
    }
}
